# ECE 196 Lecture 3: Python Packages for ML

# What we will cover today
* Numpy
* Pandas
* Scikit-Learn
* Matplotlib
* Seaborn
* Statsmodels

## Numpy

What is 
<a href="https://numpy.org/doc/stable/user/whatisnumpy.html" class="alert-link">Numpy</a>?


<div class="alert alert-success">
Numpy is a Python library for scientific computing in Python, that provides a multidimensional array object and tools to working with these arrays efficiently. Numpy allows the code to be more concise, faster, and more closely resemble standard mathematical notation.
</div>

### Arrays
The elements in a NumPy array are all required to be of the same data type.  
The shape of an array is a tuple of integers giving the size of the array along each dimension.  

In [1]:
import numpy as np

array = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
print(array)

array[0][1] = 'a string' # numpy array elements must be the same type
array2 = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(array2)
print(array2.dtype)

print(type(array))
print(type(array[0]))
print(type(array[0][0]))
print(array.shape) # prints a tuple of the array (row, col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: invalid literal for int() with base 10: 'a string'

#### Different ways to create numpy arrays

In [ ]:
a = np.zeros((2,2))            # Create an array of all zeros with specified shape
print(a)
b = np.ones((1,2))             # Create an array of all ones with specified shape
print(b)
c = np.full((2,2), 7)          # Create an array filled with specified value(s)
print(c)
d = np.eye(2)                  # Create an identity matrix with specified shape
print(d)
e = np.random.random((2,2))    # Create an array filled with random values with specified shape
print(e)
f = np.empty((3,2))            # Create an array filled with random values depending on the state of your machine
print(f)
g = np.arange(12)              # Create a 1-D array from 0 to specified value (similar to Python's built-in range)
print(g)                       # Also follows (start, stop, step)
my_list = range(2, 20, 3)
h = np.array(my_list)             # Create a numpy array from a list
print(h)
i = np.linspace(0, 100, num=9) # Create a array evenly spaced by specified intervals
# print(i)

#### freely manipulate the shape of your array

In [ ]:
array = g.reshape(4,3)
print(array)
print(array.shape)

array = array.reshape(2,6)
print(array)
print(array.shape)

array = np.arange(8).reshape(2,2,2)
print(array)
print(array.shape)

A new possible syntax for indexing

In [ ]:
my_list = [[1,1],[5,4]]
# print(my_list[1,1])
my_array = np.array(my_list)
print(my_array[1,1])
print(my_array[1][1])

Numpy allows for easier mathematical operations

In [ ]:
my_array = [[1, 2],[3, 4]]
print(my_array)
my_array2 = [[4,3],[2,1]]
print(my_array2)

my_array3 = my_array + my_array2
print(my_array3)

In [ ]:
np_array = np.array(my_array)
print(np_array)
np_array2 = np.array(my_array2)
print(np_array2)

np_array3 = np_array + np_array2
print(np_array3)