# ECE 196 Lecture 3: Python Packages for ML

# What we will cover today
* Numpy
* Pandas
* Scikit-Learn
* Matplotlib
* Seaborn
* Statsmodels

## Numpy

What is 
<a href="https://numpy.org/doc/stable/user/whatisnumpy.html" class="alert-link">Numpy</a>?


In [2]:
import numpy as np

In [1]:
my_array = [[1, 2],[3, 4]]
print(my_array)

[[1, 2], [3, 4]]


In [6]:
my_array2 = [[4,3],[2,1]]
print(my_array2)

[[4, 3], [2, 1]]


In [7]:
my_array3 = my_array + my_array2
print(my_array3)

[[1, 2], [3, 4], [4, 3], [2, 1]]


In [5]:
np_array = np.array([[1, 2],[3, 4]])
print(np_array)

[[1 2]
 [3 4]]


In [9]:
np_array2 = np.array([[4,3],[2,1]])
print(np_array2)

[[4 3]
 [2 1]]


In [10]:
np_array3 = np_array + np_array2
print(np_array3)

[[5 5]
 [5 5]]
