# Variables
* Variable name must start with a letter or the underscore character
* Variable name cannot start with a number
* Variable name can only contain: alphanumeric characters (A-z, 0-9) or underscores ( _ )
* Variable names are case sensitive

In [7]:
x = 10
print(x)
print(type(x))
y = 10.6
print(y)
x = 3.1415
print(x)
print(type(x))
x = "hello world!"
print(x)
print(type(x))

10
<class 'int'>
10.6
3.1415
<class 'float'>
hello world!
<class 'str'>


# Comments
* Inline comment with the pound ( # ) key
* Multiple-line comment with triple quotes ( ‘’’ or “”” )

In [10]:
x = 10   # this is an inline comment
print(x)
print(type(x))

'''
    THis is a multiple-line
    comment
'''
y = 10.6
print(y)
"""
    This is a multiple-line
    comment
"""
x = 3.1415
print(x)
print(type(x))
x = "hello world!"
print(x)
print(type(x))

10
<class 'int'>
10.6
3.1415
<class 'float'>
hello world!
<class 'str'>


# Math
* Three types of number in Python: **int**, **float**, and **complex**
* 4 possible operations: addition ( **+** ), subtraction ( **-** ), multiplication ( ***** ), division ( **/** )


In [20]:
x = 10
y = 10.5
z = 10 + 10.5  ## dynamically assign z to be a float
print(z)
print(type(z))

x = 5
y = 16
z = int(x / y)
print(z)

x = 10 - 5j
y = 4 + 2j
print(x)
print(type(x))
print(x.real, x.imag)
print(x + y)
print(x * y)

20.5
<class 'float'>
0
(10-5j)
<class 'complex'>
10.0 -5.0
(14-3j)
(50+0j)


# User Input
To capture input from the user, use the **input** command.

In [28]:
value = input("Enter something:")
print("value = ", value)
print(type(value))

try:
    value = int(input("Enter a number:"))
    value = value + 1
    print("value after addition: ", value)
except ValueError:
    print("ValueError: Input must be a number")
x = 5
print(x)

Enter something:ece196
value =  ece196
<class 'str'>
Enter a number:ece196
ValueError: Input must be a number


# Conditionals
**if** condition 1:

    code goes here
    
**elif** condition 2:

    code goes here

**else:**

    code goes here

In [31]:
x = 10
y = 5.0 ## float
z = 15.0

if x <= 10:
    print("x is less than 10")
    if z == 15:
        print("z = 15")
elif x >= 10 and y == 5:
    print("x is >= 10 and y equals 5")
else:
    print("else statement")

x is less than 10
z = 15


# List
Refer to the following [link](https://docs.python.org/3/tutorial/datastructures.html) for all the available function. 

In [42]:
my_grocery_list = ["apples", "bananas", 5.5, 2 + 5j] ## intialized using brackets
my_grocery_list[0] = "potatoes"
my_grocery_list[2] = 2 + 4j      ## modifying element
print(my_grocery_list)
print(type(my_grocery_list[2]))

my_grocery_list.append("apples")  ## appending element
print(my_grocery_list)

my_grocery_list.pop(1)    ## removing element
print(my_grocery_list)

my_grocery_list.insert(2, "bananas")  ## insert at specified location
print(my_grocery_list)

['potatoes', 'bananas', (2+4j), (2+5j)]
<class 'complex'>
['potatoes', 'bananas', (2+4j), (2+5j), 'apples']
['potatoes', (2+4j), (2+5j), 'apples']
['potatoes', (2+4j), 'bananas', (2+5j), 'apples']


# Tuples
Tuples works similar to list, except tuples are immutable. Refer to the following [link](https://www.tutorialspoint.com/python/python_tuples.htm) for all the available function. 

In [50]:
my_grocery_list = ("apples", "bananas", 5.5, 2 + 5j)  ## tuples are initialzed via paranthesis
print(my_grocery_list[1])
print(type(my_grocery_list))
tuple_to_list = list(my_grocery_list)
print(tuple_to_list)

# my_grocery_list.append("potatoes") ## throw an error
# my_grocery_list[1] = "potatoes"  ## throw an error
# my_grocery_list.pop()
# my_grocery_list.insert(1, 3.3)

bananas
<class 'tuple'>
['apples', 'bananas', 5.5, (2+5j)]


# Loops
## for loops
**for** *var* in *sequence*:

    code goes here

In [52]:
my_grocery_list = ["apples", "bananas", 5.5, 2 + 5j]
my_grocery_list = ("apples", "bananas", 5.5, 2 + 5j)  ## tuples are initialzed via paranthesis
for items in my_grocery_list:
    print(items)

apples
bananas
5.5
(2+5j)


## while loops
**while** stopping_condition:
    
    code goes goes
    
**Python does not support do-while loops**

In [53]:
i = 10
while i >= 0:
    print("I = ", i)
    i = i - 1

I =  10
I =  9
I =  8
I =  7
I =  6
I =  5
I =  4
I =  3
I =  2
I =  1
I =  0


# Range
Refer to the following [link](https://docs.python.org/3/library/functions.html#func-range) for further reference.

In [58]:
for i in range(7):    # provide the stopping condition
    print("i = ", i)
    
for j in range(1, 6 + 1):  # provide the starting and stopping condition
    print("j = ", j)
    
for k in range(1, 21, 3):   # provide the starting, stopping, and step condition
    print("k = ", k)

i =  0
i =  1
i =  2
i =  3
i =  4
i =  5
i =  6
j =  1
j =  2
j =  3
j =  4
j =  5
j =  6
k =  1
k =  4
k =  7
k =  10
k =  13
k =  16
k =  19


# Dictionary
Dictionaries are comma separated key-value pairs. Refer to the following [link](https://www.w3schools.com/python/python_dictionaries.asp) for further reference.

In [64]:
workout_dictionary = {"Mon": ["pushups", "situps", "squads"],
                      "Tue": "3 mile run",
                      "wed": "rest",
                      "Fri": 3.141592
                     }

print(workout_dictionary["Mon"])  ## accessing items

workout_dictionary["Mon"] = "rest" ## modify items
print(workout_dictionary)

workout_dictionary["Th"] = "3 mile run"  ## adding items
print(workout_dictionary)

['pushups', 'situps', 'squads']
{'Mon': 'rest', 'Tue': '3 mile run', 'wed': 'rest', 'Fri': 3.141592}
{'Mon': 'rest', 'Tue': '3 mile run', 'wed': 'rest', 'Fri': 3.141592, 'Th': '3 mile run'}


# Functions
**def** *functionName*( _parameters_ ):

    code goes here

In [72]:
def printMe(value):  ## function with parameter
    print(value)
    
def anotherFunction(value = "ECE196"):  ## fuction w/ default argument
    print(value)
    
def addMeAndMe(x, y = 3.1415):  ## function with and w/0 default argument
    print(x + y)
    
def testFunction(x, y = 3.14, z = 5.6):  ## function w/ multiple default argument
    print(x+y+z)
    
printMe(5)
printMe("ece196")

anotherFunction()
anotherFunction(3.1415)

addMeAndMe(3)
addMeAndMe(4, 2)

testFunction(4, z = 2)

5
ece196
ECE196
3.1415
6.141500000000001
6
9.14


# Classes
For a detail explanation of classes in Python, refer to the offical [documentation](https://docs.python.org/3/tutorial/classes.html).

**class** ClassName:
    
    <statement-1>
    .
    .
    .
    <statement-N>

In [82]:
class MyClass(object):
    
    def __init__(self, x = 4.5):
        self.myVariable = x
        print("This is the constructor for the class....")
    
    def printMe(value):  ## function with parameter
        print(value)
    
    def __anotherFunction__(self, value = "ECE196"):  ## fuction w/ default argument
        print("myVariable = ", self.myVariable)
        print(value)

    def addMeAndMe(self, x, y = 3.1415):  ## function with and w/0 default argument
        print(x + y)

    def testFunction(self, x, y = 3.14, z = 5.6):  ## function w/ multiple default argument
        print(x+y+z)
        
x = MyClass()
MyClass.printMe("ece196")
x.__anotherFunction__()

This is the constructor for the class....
ece196
myVariable =  4.5
ECE196


# Modules
For a detail explanation of modules in Python, refer to the official [documentation](https://docs.python.org/3/tutorial/modules.html).

In [99]:
import numpy as np   ## #include <numpy.h>, numpy with alias np

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

print(x)
print(y)
print(x * y)

z = np.array([[1,2], [4,5]])
w = np.array([[1, -1], [1,1]])
print("z = ")
print(z)

print("w = ")
print(w)

for row in z:
    print("row = ", row)
    for c in row:
        print("c = ", c)
        
t = np.dot(z, w)
print(t)

z_transpose = z.T
print("z_transpose = ")
print(z_transpose)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 6 14 24 36 50]
z = 
[[1 2]
 [4 5]]
w = 
[[ 1 -1]
 [ 1  1]]
row =  [1 2]
c =  1
c =  2
row =  [4 5]
c =  4
c =  5
[[3 1]
 [9 1]]
z_transpose = 
[[1 4]
 [2 5]]
