# ECE 196 Lecture 1: Intro to Python

# Jupyter Notebook

<div class="alert alert-success">
Jupyter notebook is a tool that combines executable code, code outputs, and text into a single file.
</div>

<div class="alert alert-success">
The main organizational structure of the notebook are 'cells'.
</div>

<div class="alert alert-info">
For more useful information, check out Jupyter Notebooks 
<a href="https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/" class="alert-link">tips & tricks</a>
.
The official documentation from project Jupyter is available 
<a href="https://jupyter-notebook.readthedocs.io/en/stable/" class="alert-link">here</a>
and some example notebooks can be found
<a href="https://github.com/jupyter/notebook/tree/master/docs/source/examples/Notebook" class="alert-link">here</a>
.
</div>

<center><img src="media/meme1.png" width="900px"></center>

# Variables
* Variable name must start with a letter or the underscore character
* Variable name cannot start with a number
* Variable name can only contain: alphanumeric characters (A-z, 0-9) or underscores ( _ )
* Variable names are case sensitive

In [1]:
dragon_warrior = 'Po'
Dragon_Warrior = 'kung fu panda'
print(dragon_warrior)
print(Dragon_Warrior)

Po
kung fu panda


### Reserved Words

There are 33 words that are not allowed to be used for variable assignment in Python.

<table type="text/css">
  <tr>
      <td><code>False</code></td>
      <td><code>None</code></td>
      <td><code>True</code></td>
      <td><code>and</code></td>
      <td><code>as</code></td>
      <td><code>assert</code></td>
      <td><code>break</code></td>
  </tr>
  <tr>
      <td><code>class</code></td>
      <td><code>continue</code></td>
      <td><code>def</code></td>
      <td><code>del</code></td>
      <td><code>elif</code></td>
      <td><code>else</code></td>
      <td><code>except</code></td>
  </tr>
  <tr>
      <td><code>finally</code></td>
      <td><code>for</code></td>
      <td><code>from</code></td>
      <td><code>global</code></td>
      <td><code>if</code></td>
      <td><code>import</code></td>
      <td><code>in</code></td>
  </tr>
  <tr>
      <td><code>is</code></td>
      <td><code>lambda</code></td>
      <td><code>nonlocal</code></td>
      <td><code>not</code></td>
      <td><code>or</code></td>
      <td><code>pass</code></td>
      <td><code>raise</code></td>
  </tr>    
  <tr>
      <td><code>return</code></td>
      <td><code>try</code></td>
      <td><code>while</code></td>
      <td><code>with</code></td>
      <td><code>yield</code></td>
  </tr>    
</table>

### Variable Types
<div class="alert alert-success">
<b>Integers</b> store whole numbers.
</div>

In [2]:
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


### Variable Types
<div class="alert alert-success">
<b>Floats</b> store signed, decimal-point numbers.
</div>

In [3]:
my_float = 10.6
print(my_float)
print(type(my_float))

my_float = -3.14
print(my_float)
print(type(my_float))

10.6
<class 'float'>
-3.14
<class 'float'>


### Variable Types
<div class="alert alert-success">
<b>Strings</b> store characters, as text. 
</div>

In [4]:
my_string = 'ECE 196 is awesome!'
print(my_string)
print(type(my_string))

ECE 196 is awesome!
<class 'str'>


### Variable Types
<div class="alert alert-success">
<b>Booleans</b> store "True" or "False". 
</div>

In [21]:
my_bool = True
print(my_bool)
print(type(my_bool))

my_bool = False
print(my_bool)
print(type(my_bool))

True
<class 'bool'>
False
<class 'bool'>


### Variable Types
<div class="alert alert-success">
"None" is a special type that stores "None", used to denote a null or empty value.
</div>

In [22]:
empty_var = None
print(empty_var)
print(type(empty_var))

None
<class 'NoneType'>


# Comments
* Inline comment with the pound ( `#` ) key
* Multiple-line comment with triple quotes ( `‘’’` or `“””` )

In [7]:
x = 10   # this is an inline comment
print(x)
print(type(x))

'''
    THis is a multiple-line
    comment
'''
y = 10.6
print(y)
"""
    This is a multiple-line
    comment
"""
x = 3.1415
print(x)
print(type(x))
x = "hello world!"
print(x)
print(type(x))

10
<class 'int'>
10.6
3.1415
<class 'float'>
hello world!
<class 'str'>


# Operators
* assignment
* math
* logic
* comparison

## Assignment
#### Code Variables != Math Variables
* In mathematics: `=` refers to equality (as a statement of truth).
* In coding: `=` refers to assignment.

Math: What is x?

$x = 2x + 2$

$-x = 2$

$x = -2$

Code: What is x?

`x = x + 1`

In [8]:
my_var = 2 
my_var = my_var + 1

What is my_var?

A) 0

B) 2

C) 3

D) "my_var + 1"

## Math
* Three types of number in Python: **int**, **float**, and **complex**
* addition ( `+` ), subtraction ( `-` ), multiplication ( `*` ), division ( `/` ), exponentiation ( `**` ), modulus ( `%` ), floor division ( `//` )

In [9]:
x = 10
y = 10.5
z = 10 + 10.5  ## dynamically assign z to be a float
print(z)
print(type(z))

x = 5
y = 16
z = int(x / y)
print(z)

x = 10 - 5j
y = 4 + 2j
print(x)
print(type(x))
print(x.real, x.imag)
print(x + y)
print(x * y)

20.5
<class 'float'>
0
(10-5j)
<class 'complex'>
10.0 -5.0
(14-3j)
(50+0j)


## Logic (Boolean)
* `and` : True if both are true
* `or` : True if at least one is true
* `not` : True only if false

## Comparison Operators
<div class="alert alert-success">
Python has comparison operators <code>==</code>, <code>!=</code>, <code><</code>, <code>></code>, <code><=</code>, and <code>>=</code> for value comparisons. These operators return booleans.
</div>

* `==` : values are equal
* `!=` : values are not equal
* `<` : value on left is less than value or right
* `>` : value on left is greater than value on right
* `<=` : value on left is less than *or equal to* value on right
* `>=` : value on left is greater than or equal to value on the right

In [30]:
a = 5
b = 5
c = 10
d = 50

a*b > d

False

# User Input
To capture input from the user, use the **input** command.

In [10]:
value = input("Enter something:")
print("value = ", value)
print(type(value))

# try:
#     value = int(input("Enter a number:"))
#     value = value + 1
#     print("value after addition: ", value)
# except ValueError:
#     print("ValueError: Input must be a number")
# x = 5
# print(x)

Enter something:5
value =  5
<class 'str'>


# Indentations

# Conditionals
* `if`
* `elif`
* `else`

<div class="alert alert-success">
Conditionals are statements that check for a condition, using the <code>if</code> statement, and then only execute a set of code if the condition evaluates as <code>True</code>.
</div>

<div class="alert alert-success">
After an <code>if</code> statement, you can have any number of <code>elif</code>`s (meaning 'else if') to check other conditions.
</div>

<div class="alert alert-success">
After an <code>if</code>, you can use an <code>else</code> that will run if the conditional(s) above have not run.
</div>

**if** condition 1:

    code goes here
    
**elif** condition 2:

    code goes here

**else:**

    code goes here

## Properties of conditionals

- All conditionals start with an `if`, can have an optional and variable number of `elif`'s and an optional `else` statement
- Conditionals can take any expression that can be evaluated as `True` or `False`. 
- At most one component (`if` / `elif` / `else`) of a conditional will run
- The order of conditional blocks is always `if` then `elif`(s) then `else`
- Code is only ever executed if the condition is met

In [11]:
ECE196 = input("How do you like ECE 196? ")

if ECE196 == 'Amazing':
    print('Hoooray!')
elif ECE196 == 'Great':
    print('Thank you!')
elif ECE196 == 'Good':
    print('We appreciate the feedback!')
else:
    print('We will work hard to improve!')

Thank you!


# Collections

# List
Refer to the following [link](https://docs.python.org/3/tutorial/datastructures.html) for all the available function.

<div class="alert alert-success">
A <b>list</b> is a mutable collection of ordered items, that can be of mixed type. Lists are created using square brackets.
</div>

In [12]:
my_grocery_list = ["apples", "bananas", 5.5, 2 + 5j] ## intialized using brackets
my_grocery_list[0] = "potatoes"
my_grocery_list[2] = 2 + 4j      ## modifying element
print(my_grocery_list)
print(type(my_grocery_list[2]))

my_grocery_list.append("apples")  ## appending element
print(my_grocery_list)

my_grocery_list.pop(1)    ## removing element
print(my_grocery_list)

my_grocery_list.insert(2, "bananas")  ## insert at specified location
print(my_grocery_list)

['potatoes', 'bananas', (2+4j), (2+5j)]
<class 'complex'>
['potatoes', 'bananas', (2+4j), (2+5j), 'apples']
['potatoes', (2+4j), (2+5j), 'apples']
['potatoes', (2+4j), 'bananas', (2+5j), 'apples']


In [ ]:
# indexing and slicing


* Negative indices index backwards through a collection
* A sequence of indices (called a slice) can be accessed using `start:stop`
* In this contstruction, `start` is included then every element until `stop`, not including `stop` itself
* To skip values in a sequence use `start:stop:step`

# Tuples
Tuples works similar to list, except tuples are immutable. Refer to the following [link](https://www.tutorialspoint.com/python/python_tuples.htm) for all the available function. 

<div class="alert alert-success">
A <b>tuple</b> is an <i>immutable</i> collection of ordered items, that can be of mixed type. Tuples are created using parentheses.
</div>

In [13]:
my_grocery_list = ("apples", "bananas", 5.5, 2 + 5j)  ## tuples are initialzed via paranthesis
print(my_grocery_list[1])
print(type(my_grocery_list))
tuple_to_list = list(my_grocery_list)
print(tuple_to_list)

# my_grocery_list.append("potatoes") ## throw an error
# my_grocery_list[1] = "potatoes"  ## throw an error
# my_grocery_list.pop()
# my_grocery_list.insert(1, 3.3)

bananas
<class 'tuple'>
['apples', 'bananas', 5.5, (2+5j)]


## Pay attention to Aliases!

In [ ]:
# Make a variable & an alias
# change value of original variable
# Ints are immutable
a = 1
b = a
a = 2

print(a)
print(b)

In [ ]:
# Lists are mutable
first_list = [1, 2, 3, 4]
alias_list = first_list
#change second value of first_list
first_list[1] = 29
alias_list

## Strings are also collection of characters!

In [ ]:
# Define a string
my_str = 'TheFamousFive'
# Index into a string
my_str[2]
# Ask if an item is in a string
'Fam' in my_str
# Check the length of a string
len(my_str)
# Index into a string
# This code will produce an error
my_str[1:3] = 'HE'

# Loops
## for loops
**for** *var* in *sequence*:

    code goes here

In [14]:
my_grocery_list = ["apples", "bananas", 5.5, 2 + 5j]
my_grocery_list = ("apples", "bananas", 5.5, 2 + 5j)  ## tuples are initialzed via paranthesis
for items in my_grocery_list:
    print(items)

apples
bananas
5.5
(2+5j)


## while loops
**while** stopping_condition:
    
    code goes goes
    
**Python does not support do-while loops**

In [15]:
i = 10
while i >= 0:
    print("I = ", i)
    i = i - 1

I =  10
I =  9
I =  8
I =  7
I =  6
I =  5
I =  4
I =  3
I =  2
I =  1
I =  0


## Range
<div class="alert alert-success">
<code>range</code> is an operator to create a range of numbers, that is often used with loops.
</div>

Refer to the following [link](https://docs.python.org/3/library/functions.html#func-range) for further reference.

In [16]:
for i in range(7):    # provide the stopping condition
    print("i = ", i)
    
for j in range(1, 6 + 1):  # provide the starting and stopping condition
    print("j = ", j)
    
for k in range(1, 21, 3):   # provide the starting, stopping, and step condition
    print("k = ", k)

i =  0
i =  1
i =  2
i =  3
i =  4
i =  5
i =  6
j =  1
j =  2
j =  3
j =  4
j =  5
j =  6
k =  1
k =  4
k =  7
k =  10
k =  13
k =  16
k =  19


Write a loop that adds all the odd numbers between 1 and 100 together.

A)  
`
summation = 0
for num in range(100):
    summation += num
print(summation)
`  
B)  
`
summation = 0
for num in range(0,101,2):
    summation += num
print(summation)
`  
C)  
`
summation = 0
for num in range(1,100,2):
    summation += num
print(summation)
`  
D)  
None of above

## Continue and Break

<div class="alert alert-success">
<code>continue</code> is a special operator to jump ahead to the next iteration of a loop.
</div>

<div class="alert alert-success">
<code>break</code> is a special operator to break out of a loop.
</div>

# Dictionary
<div class="alert alert-success">
A dictionary is mutable collection of items, that can be of mixed-type, that are stored as key-value pairs.
</div>

Dictionaries are comma separated key-value pairs. Refer to the following [link](https://www.w3schools.com/python/python_dictionaries.asp) for further reference.
- Only one value per key. No duplicate keys allowed. 
    - If duplicate keys specified during assignment, the last assignment wins.
   - **keys** must be of an immutable type (string, tuple, integer, float, etc)
- Note: **values** can be of any type


In [17]:
workout_dictionary = {"Mon": ["pushups", "situps", "squads"],
                      "Tue": "3 mile run",
                      "wed": "rest",
                      "Fri": 3.141592
                     }

print(workout_dictionary["Mon"])  ## accessing items

workout_dictionary["Mon"] = "rest" ## modify items
print(workout_dictionary)

workout_dictionary["Th"] = "3 mile run"  ## adding items
print(workout_dictionary)

['pushups', 'situps', 'squads']
{'Mon': 'rest', 'Tue': '3 mile run', 'wed': 'rest', 'Fri': 3.141592}
{'Mon': 'rest', 'Tue': '3 mile run', 'wed': 'rest', 'Fri': 3.141592, 'Th': '3 mile run'}


What will the code print?

In [5]:
guesses = {'Matt' : [2, 8], 
           'Jason'  : [12, 18],
           'Lee' : [7, 11]}
answer = 10

for item in guesses:
    temp = guesses[item]
    if temp[0] <= answer <= temp[1]:
        winner = item
        
# print(winner)

* A) Matt
* B) [7, 11] 
* C) Jason
* D) Lee
* E) Matt, Jason

# Functions
**def** *functionName*( _parameters_ ):

    code goes here

In [18]:
def printMe(value):  ## function with parameter
    print(value)
    
def anotherFunction(value = "ECE196"):  ## fuction w/ default argument
    print(value)
    
def addMeAndMe(x, y = 3.1415):  ## function with and w/0 default argument
    print(x + y)
    
def testFunction(x, y = 3.14, z = 5.6):  ## function w/ multiple default argument
    print(x+y+z)
    
printMe(5)
printMe("ece196")

anotherFunction()
anotherFunction(3.1415)

addMeAndMe(3)
addMeAndMe(4, 2)

testFunction(4, z = 2)

5
ece196
ECE196
3.1415
6.141500000000001
6
9.14


# Classes
For a detail explanation of classes in Python, refer to the offical [documentation](https://docs.python.org/3/tutorial/classes.html).

**class** ClassName:
    
    <statement-1>
    .
    .
    .
    <statement-N>

In [19]:
class MyClass(object):
    
    def __init__(self, x = 4.5):
        self.myVariable = x
        print("This is the constructor for the class....")
    
    def printMe(value):  ## function with parameter
        print(value)
    
    def __anotherFunction__(self, value = "ECE196"):  ## fuction w/ default argument
        print("myVariable = ", self.myVariable)
        print(value)

    def addMeAndMe(self, x, y = 3.1415):  ## function with and w/0 default argument
        print(x + y)

    def testFunction(self, x, y = 3.14, z = 5.6):  ## function w/ multiple default argument
        print(x+y+z)
        
x = MyClass()
MyClass.printMe("ece196")
x.__anotherFunction__()

This is the constructor for the class....
ece196
myVariable =  4.5
ECE196


# Modules
For a detail explanation of modules in Python, refer to the official [documentation](https://docs.python.org/3/tutorial/modules.html).

In [20]:
import numpy as np   ## #include <numpy.h>, numpy with alias np

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

print(x)
print(y)
print(x * y)

z = np.array([[1,2], [4,5]])
w = np.array([[1, -1], [1,1]])
print("z = ")
print(z)

print("w = ")
print(w)

for row in z:
    print("row = ", row)
    for c in row:
        print("c = ", c)
        
t = np.dot(z, w)
print(t)

z_transpose = z.T
print("z_transpose = ")
print(z_transpose)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 6 14 24 36 50]
z = 
[[1 2]
 [4 5]]
w = 
[[ 1 -1]
 [ 1  1]]
row =  [1 2]
c =  1
c =  2
row =  [4 5]
c =  4
c =  5
[[3 1]
 [9 1]]
z_transpose = 
[[1 4]
 [2 5]]
